services:
  spring-app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  angular-app:
    build:
      context: ./frontend-beer-frontier
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
