/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import type { Brewery } from '../models/index';
import { BreweryFromJSON, BreweryToJSON } from '../models/index';

export interface GetBreweryByIdRequest {
  id: number;
}

/**
 *
 */
export class BreweryControllerApi extends runtime.BaseAPI {
  /**
   */
  async getBreweriesRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Array<Brewery>>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/breweries`,
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue =>
      jsonValue.map(BreweryFromJSON)
    );
  }

  /**
   */
  async getBreweries(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Array<Brewery>> {
    const response = await this.getBreweriesRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async getBreweryByIdRaw(
    requestParameters: GetBreweryByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<Brewery>> {
    if (requestParameters['id'] == null) {
      throw new runtime.RequiredError(
        'id',
        'Required parameter "id" was null or undefined when calling getBreweryById().'
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    const response = await this.request(
      {
        path: `/breweries/{id}`.replace(
          `{${'id'}}`,
          encodeURIComponent(String(requestParameters['id']))
        ),
        method: 'GET',
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, jsonValue =>
      BreweryFromJSON(jsonValue)
    );
  }

  /**
   */
  async getBreweryById(
    requestParameters: GetBreweryByIdRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<Brewery> {
    const response = await this.getBreweryByIdRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
